### ISSUE TITLE
Switch to codecov

### ISSUE THREAD

**Issue by Kubuxu** [libp2p/go-libp2p-raft#15]
Codecov has much better UI and integration. If you have nothing against it I could switch this repo to it.

**Comment by Kubuxu** [comment]
What I mean by integration: for example browser plugin that shows file coverage directly in the Github diff or file browser: https://github.com/codecov/browser-extension

**Comment by hsanjuan** [comment]
I'm not in need, but if you want to do it send a PR :)

**Comment by hsanjuan** [comment]
seems done
