### ISSUE TITLE
transport.go文件中变量logLogger和NetworkTransportConfig中logger类型不匹配

### ISSUE THREAD

**Issue by wxw9868** [libp2p/go-libp2p-raft#65]
https://github.com/libp2p/go-libp2p-raft/blob/master/transport.go
中的
var **logLogger** = log.New(&logForwarder{}, "", 0)
和
cfg := &raft.NetworkTransportConfig{
		ServerAddressProvider: provider,
		Logger:                **logLogger**,
		Stream:                stream,
		MaxPool:               0,
		Timeout:               timeout,
}
中的Logge类型不匹配，导致了错误，请尽快改正。

**Comment by hsanjuan** [comment]
Make sure you are using the raft version from the project's go.mod file (v1.1.1). Newer versions do not work.
