### ISSUE TITLE
fsm Snapshot BUG

### ISSUE THREAD

**Issue by zeigo** [libp2p/go-libp2p-raft#69]
As hashicorp/raft says, https://github.com/hashicorp/raft/blob/f7242e76aa8944d87eceda619705c3ac208b8aef/fsm.go#L54
Calling `fsm.Apply()` and `fsmSnapshot.Persist()` must be concurrent safe, I think the current implementation is not correct.
Consider a case, the fsm has applied logs from 1 to 10. Then, `fsm.Snapshot()` and `fsmSnapshot.Persist()` are called,  it should produce a snapshot matching logs [1,10]. `Persist()` will get the mutex inside `fsm`, encode fsm.state, and write to sink. However, if `Apply()` happens between `Snapshot()` and `Persist()`, and get the mutex before `Persist()`, it will update fsm.state, so the content wrote to sink will not match to logs [1,10], instead [1,11].

**Comment by zeigo** [comment]
To demonstrate, boot a raft cluster with only one member, set a rather small snapshot threshhold, and commit many operation. Then you can find the snapshot content do not match with the snapshot metadata(like index).

I create a `State` with a int value, and applying `LogOp` will add it by 1. The following is some debug info.
```
latest index 3, current state 1
latest index 203, current state 201
snapshot encoded value  389
write to sink: index  383
latest index 403, current state 401
latest index 603, current state 601
latest index 803, current state 801
snapshot encoded value  865
write to sink: index  865
```
You can see, after log entry `i` is applied, state should be `i - 2`. So, if I take snapshot on logs not larger than `i`, it should match the state `i - 2`. Howerver, it dont satisfy.

**Comment by hsanjuan** [comment]
What is your proposal to fix it? Is it just matter of locking?
