### ISSUE TITLE
Fails to build with github.com/hashicorp/raft newer than v1.1.1

### ISSUE THREAD

**Issue by smartin015** [libp2p/go-libp2p-raft#78]
To reproduce:

Use `import github.com/libp2p/go-libp2p-raft` in a go project, then get the release after v1.1.1 of hashicorp raft ([v1.2.0](https://github.com/hashicorp/raft/releases/tag/v1.2.0) was released 2020-10-05, around 2 years ago)

```
go get github.com/libp2p/go-libp2p-raft
go get github.com/hashicorp/raft@v1.2.0
go build .
```

Receives the following error:

```
# github.com/libp2p/go-libp2p-raft
../../../../go/pkg/mod/github.com/libp2p/go-libp2p-raft@v0.2.0/transport.go:126:26: cannot use logLogger (variable of type *"log".Logger) as type hclog.Logger in struct literal:
        *"log".Logger does not implement hclog.Logger (missing Debug method)
```

The culprit seems to be [this PR](https://github.com/hashicorp/raft/commit/635796e5097fbfdb80f6f2d92abe66739a957380) which uses a new logging interface that is incompatible with golang's default "log" package. The "easiest" fix would be to use `hclog.Default()` per [here](https://github.com/hashicorp/go-hclog#use-the-global-logger), assuming there isn't additional logging configuration needed.

**Comment by hsanjuan** [comment]
See #77
